export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'COMPLETE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'

export const TODO_ALL = 'ALL'
export const TODO_COMPLETED = 'COMPLETED'
export const TODO_INCOMPLETED = 'INCOMPLETED'

export const FILTER_TODO_BY_STATE = 'FILTER_TODO_BY_STATE'
export const FILTER_TODO_BY_KEYWORD = 'FILTER_TODO_BY_KEYWORD'
